### ISSUE TITLE
[SQL: SELECT name.name AS name_name  FROM name] (Background on this error at: http://sqlalche.me/e/13/e3q8) Error

### ISSUE THREAD

**Issue by malimba** [PizzaMyHeart/muler#1]
I tried to run your app but it seems there's a problem with the SQL_ALCHEMY config.Need help? or is there a fix you can make soon?

**Comment by PizzaMyHeart** [comment]
Are you running it with test.db? It has a different schema than the actual db used by the app - sorry about that, will create a proper test db with dummy data soon.

**Comment by malimba** [comment]
Alright.Thanks for the update.

**Comment by malimba** [comment]
Alright.Thanks for the update.

**Comment by PizzaMyHeart** [comment]
I've uploaded muler.db and it should run properly now. I wasn't sure about the licensing issues initially but I've had a closer look and looks like it's ok for me to share it. 

Apologies for the delay!

**Comment by malimba** [comment]
thanks
